7

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,14 +16,9 @@ jobs:
       run: npm install
     
     - name: Compile TypeScript files
-      run: npx tsc
+      run: |
+        npx tsc || (echo "TypeScript compilation failed" && exit 1)
     
     - name: Run Test1
       run: |
-        output=$(node dist/Test1.js)
-        exit_code=$output
-
-        if [ $exit_code -ne 0 ]; then
-          echo "Error $exit_code"
-          exit 1
-        fi
+        node dist/Test1.js
