testt

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,12 +16,12 @@ jobs:
       run: npm install
     
     - name: Run Test1
-      run: |
-        output=$(node dist/Test1.js)
-        exit_code=$output
+      run: npm test
+        # output=$(node dist/Test1.js)
+        # exit_code=$output
 
-        if [ $exit_code -ne 0 ]; then
-          echo "Error $exit_code"
-          exit 1
-        fi
+        # if [ $exit_code -ne 0 ]; then
+        #   echo "Error $exit_code"
+        #   exit 1
+        # fi
 
